# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scripts\../ui\video.ui'
#
# Created: Tue Mar 25 13:01:47 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(801, 848)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.grid = QtGui.QGridLayout()
        self.grid.setObjectName("grid")
        self.verticalLayout.addLayout(self.grid)
        self.playback = QtGui.QGroupBox(self.centralwidget)
        self.playback.setGeometry(QtCore.QRect(10, 670, 779, 151))
        self.playback.setTitle("")
        self.playback.setObjectName("playback")
        self.load_label_2 = QtGui.QLabel(self.playback)
        self.load_label_2.setGeometry(QtCore.QRect(10, 120, 71, 16))
        self.load_label_2.setObjectName("load_label_2")
        self.load_meter = QtGui.QProgressBar(self.playback)
        self.load_meter.setGeometry(QtCore.QRect(10, 30, 761, 21))
        self.load_meter.setProperty("value", 24)
        self.load_meter.setObjectName("load_meter")
        self.audio = QtGui.QComboBox(self.playback)
        self.audio.setGeometry(QtCore.QRect(80, 120, 241, 20))
        self.audio.setObjectName("audio")
        self.load_label = QtGui.QLabel(self.playback)
        self.load_label.setGeometry(QtCore.QRect(10, 10, 371, 20))
        self.load_label.setObjectName("load_label")
        self.slider = QtGui.QSlider(self.playback)
        self.slider.setGeometry(QtCore.QRect(10, 60, 761, 22))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.play_btn = QtGui.QPushButton(self.playback)
        self.play_btn.setGeometry(QtCore.QRect(10, 90, 311, 23))
        self.play_btn.setObjectName("play_btn")
        self.volume = QtGui.QSlider(self.playback)
        self.volume.setGeometry(QtCore.QRect(340, 90, 22, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume.sizePolicy().hasHeightForWidth())
        self.volume.setSizePolicy(sizePolicy)
        self.volume.setOrientation(QtCore.Qt.Vertical)
        self.volume.setObjectName("volume")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionPlay_Pause = QtGui.QAction(MainWindow)
        self.actionPlay_Pause.setObjectName("actionPlay_Pause")
        self.open_file = QtGui.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.exit = QtGui.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.menuFile.addAction(self.open_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "CH10 Video Player", None, QtGui.QApplication.UnicodeUTF8))
        self.load_label_2.setText(QtGui.QApplication.translate("MainWindow", "Audio Source:", None, QtGui.QApplication.UnicodeUTF8))
        self.load_label.setText(QtGui.QApplication.translate("MainWindow", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.play_btn.setText(QtGui.QApplication.translate("MainWindow", "Play / Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlay_Pause.setText(QtGui.QApplication.translate("MainWindow", "Play / Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.open_file.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.open_file.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.exit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

